import os
import time
import json
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from sqlmodel import SQLModel, create_engine, Session, select
from models import User, Task, PointsLog, Snapshot
from crypto import encrypt_token, decrypt_token
from leetcode import fetch_leetcode_stats, fetch_recent_ac, fetch_problem
from github import count_repo_commits
from planner import generate_roadmap, generate_overview

load_dotenv() 

DATABASE_URL = os.getenv('DATABASE_URL')

# Only build the engine if a URL is present, so importing this module doesn't
# crash when DATABASE_URL is missing (e.g. on Vercel, which isn't configured
# with it yet). Locally it comes from .env, so the engine works normally.
engine = create_engine(DATABASE_URL) if DATABASE_URL else None

def create_db_and_tables():
    SQLModel.metadata.create_all(engine)

def save_user(github_id, access_token):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user == None:
                user = User(github_id=github_id, github_token=encrypt_token(access_token))
        else:
                user.github_token = encrypt_token(access_token)
        session.add(user)
        session.commit()

def get_user(github_id):
    with Session(engine) as session:
        return session.exec(select(User).where(User.github_id == github_id)).first()

def delete_user_data(github_id):
    # Wipe everything for this user, including the account row itself.
    with Session(engine) as session:
        for model in (Task, PointsLog, Snapshot):
            for row in session.exec(select(model).where(model.github_id == github_id)).all():
                session.delete(row)
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is not None:
            session.delete(user)
        session.commit()

def set_leetcode_username(github_id, username):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user == None:
            return
        else:
            user.leetcode_username = username
        session.add(user)
        session.commit()

def set_tracked_repo(github_id, repo):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is None:
            return
        user.tracked_repo = repo
        session.add(user)
        session.commit()

def save_leetcode_stats(github_id, easy, medium, hard):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is None:
            return
        user.leetcode_easy = easy
        user.leetcode_medium = medium
        user.leetcode_hard = hard
        user.leetcode_updated_at = time.time()   # record WHEN we cached it (Unix seconds)
        session.add(user)
        session.commit()


# A hardcoded starter roadmap. New users get seeded with these (Phase 3 template).
# (title, points, metric, target) — metric None = manual task (not auto-detected).
STARTER_TASKS = [
    ("Solve 5 easy LeetCode problems", 10, "easy", 5),
    ("Solve 3 medium LeetCode problems", 20, "medium", 3),
    ("Solve 1 hard LeetCode problem", 25, "hard", 1),
    ("Make 5 GitHub commits", 10, None, None),
    ("Merge 1 pull request", 15, None, None),
]

def get_tasks(github_id):
    # Just return stored tasks — they're generated by the AI planner when the
    # user sets a goal (never generated here, so page loads don't call Gemini).
    with Session(engine) as session:
        tasks = session.exec(select(Task).where(Task.github_id == github_id)).all()
        return [
            {"id": t.id, "title": t.title, "points": t.points,
             "completed": t.completed, "resource_url": t.resource_url,
             "metric": t.metric, "target": t.target}
            for t in tasks
        ]


def replace_tasks(github_id, tasks):
    with Session(engine) as session:
        for old in session.exec(select(Task).where(Task.github_id == github_id)).all():
                session.delete(old)
        for t in tasks:
            session.add(Task(
                github_id=github_id,
                title=t["title"],
                points=t["points"],
                metric=t.get("metric"),
                target=t.get("target"),
                resource_url=t.get("resource_url"),
                leetcode_slug=t.get("leetcode_slug"),
            ))
        session.commit()


def set_goal_and_plan(github_id, goal):
    # Save the goal + a start-to-finish overview, then build the first daily plan.
    # The overview is generated once here (stable), not on every daily refresh.
    try:
        overview = json.dumps(generate_overview(goal))
    except Exception:
        overview = None   # don't let an overview hiccup block goal-setting
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is None:
            return []
        user.big_goal = goal
        user.plan_overview = overview
        user.goal_started_at = time.time()   # progress resets: counts from now on
        session.add(user)
        session.commit()
    return regenerate_plan(github_id)


def _progress_context(github_id):
    # A short natural-language summary of what the user has done, so Gemini can
    # generate the NEXT day's tasks instead of repeating from scratch.
    user = get_user(github_id)
    lines = []
    if user and user.leetcode_username:
        e = user.leetcode_easy or 0
        m = user.leetcode_medium or 0
        h = user.leetcode_hard or 0
        lines.append(f"LeetCode solved so far: {e} easy, {m} medium, {h} hard.")
    snap = get_last_snapshot(github_id)
    if user and user.tracked_repo and snap:
        lines.append(f"Their tracked repo {user.tracked_repo} has {snap['commit_count']} commits.")
    log = get_points_log(github_id)
    if log:
        recent = "; ".join(l["task_title"] for l in log[:10])
        lines.append(f"Tasks they've already completed: {recent}.")
    else:
        lines.append("They are just getting started (no completed tasks yet).")
    return "Here is their progress so far:\n" + "\n".join("- " + l for l in lines)


def regenerate_plan(github_id):
    # Build a fresh daily task list for the user's existing goal, then stamp the
    # time so the 24h cycle restarts. Keeps PointsLog (streak/history) intact.
    user = get_user(github_id)
    if user is None or user.big_goal is None:
        return []
    overview = json.loads(user.plan_overview) if user.plan_overview else None
    tasks = generate_roadmap(user.big_goal, _progress_context(github_id), overview)
    replace_tasks(github_id, tasks)
    with Session(engine) as session:
        u = session.exec(select(User).where(User.github_id == github_id)).first()
        u.plan_updated_at = time.time()
        session.add(u)
        session.commit()
    return get_tasks(github_id)


# Daily plans roll over at midnight US Pacific time (not a rolling 24h window).
PACIFIC = ZoneInfo("America/Los_Angeles")

def _plan_is_stale(user):
    # Stale if the plan was last generated on an earlier Pacific calendar day
    # (or never) — i.e. a new day has started since.
    if user.plan_updated_at is None:
        return True
    last_day = datetime.fromtimestamp(user.plan_updated_at, PACIFIC).date()
    today = datetime.now(PACIFIC).date()
    return last_day < today

def refresh_plan_if_stale(github_id):
    # Regenerate this user's plan if a new Pacific day has begun. Called on app
    # load so tasks roll over at midnight even without the cron.
    user = get_user(github_id)
    if user is None or user.big_goal is None:
        return False
    if _plan_is_stale(user):
        regenerate_plan(github_id)
        return True
    return False

def regenerate_stale_plans():
    # Cron helper: refresh every user whose plan is from a previous Pacific day.
    regenerated = []
    for github_id in get_all_user_ids():
        user = get_user(github_id)
        if user is None or user.big_goal is None:
            continue
        if _plan_is_stale(user):
            regenerate_plan(github_id)
            regenerated.append(github_id)
    return regenerated

def complete_task(github_id, task_id):
    with Session(engine) as session:
        # Match BOTH id and github_id, so a user can only complete THEIR OWN task
        # (can't flip someone else's task by guessing an id).
        task = session.exec(
            select(Task).where(Task.id == task_id, Task.github_id == github_id)
        ).first()
        if task is None:
            return None
        if task.completed:
            return {"id": task.id, "points": 0}   # already done → don't double-award
        task.completed = True
        session.add(task)
        # Log the award (powers history + streak).
        session.add(PointsLog(
            github_id=github_id,
            task_title=task.title,
            points=task.points,
            created_at=time.time(),
        ))
        session.commit()
        return {"id": task.id, "points": task.points}


def get_points_log(github_id):
    with Session(engine) as session:
        logs = session.exec(
            select(PointsLog)
            .where(PointsLog.github_id == github_id)
            .order_by(PointsLog.created_at.desc())   # newest first
        ).all()
        return [
            {"task_title": l.task_title, "points": l.points, "created_at": l.created_at}
            for l in logs
        ]


def get_streak(github_id):
    # Consecutive days (UTC) on which the user earned points.
    with Session(engine) as session:
        logs = session.exec(select(PointsLog).where(PointsLog.github_id == github_id)).all()

    # Set of distinct dates the user was active.
    days = {datetime.fromtimestamp(l.created_at, tz=timezone.utc).date() for l in logs}
    if not days:
        return 0

    today = datetime.now(timezone.utc).date()
    # Anchor on today if active today, else yesterday (a streak isn't "broken"
    # until a whole day passes with no activity).
    if today in days:
        day = today
    elif (today - timedelta(days=1)) in days:
        day = today - timedelta(days=1)
    else:
        return 0

    # Walk backwards day by day while each day has activity.
    streak = 0
    while day in days:
        streak += 1
        day -= timedelta(days=1)
    return streak

def save_snapshot(github_id, easy, medium, hard, commit_count):
    with Session(engine) as session:
        snap = Snapshot(
            github_id=github_id,
            leetcode_easy=easy,
            leetcode_medium=medium,
            leetcode_hard=hard,
            commit_count=commit_count,
            created_at=time.time(),
        )
        session.add(snap)
        session.commit()

def get_last_snapshot(github_id):
    with Session(engine) as session:
        snap = session.exec(select(Snapshot).where(Snapshot.github_id == github_id).order_by(Snapshot.created_at.desc())).first()  
    if snap is None:
        return None
    return {
        "leetcode_easy": snap.leetcode_easy,
        "leetcode_medium": snap.leetcode_medium,
        "leetcode_hard": snap.leetcode_hard,
        "commit_count": snap.commit_count,
        "created_at": snap.created_at,
    }


def capture_snapshot(github_id):
    # Fetch the user's CURRENT LeetCode + GitHub numbers and save them as a snapshot.
    user = get_user(github_id)
    # Nothing to track if they've connected neither signal.
    if user is None or (user.leetcode_username is None and user.tracked_repo is None):
        return None

    # LeetCode side (only if they gave a username).
    if user.leetcode_username:
        stats = fetch_leetcode_stats(user.leetcode_username)
        easy = stats.get("Easy", 0)
        medium = stats.get("Medium", 0)
        hard = stats.get("Hard", 0)
    else:
        easy = medium = hard = 0

    # GitHub side (only if they picked a repo to track). Runs from the cron with
    # no live login, so we decrypt the stored token and call GitHub directly.
    if user.tracked_repo:
        commit_count = count_repo_commits(user.tracked_repo, decrypt_token(user.github_token))
    else:
        commit_count = 0

    save_snapshot(github_id, easy, medium, hard, commit_count)
    return {"easy": easy, "medium": medium, "hard": hard, "commits": commit_count}


def get_all_user_ids():
    with Session(engine) as session:
        return [u.github_id for u in session.exec(select(User)).all()]


def run_detection(github_id):
    # 1. Capture a fresh snapshot; this also gives us the current counts.
    current = capture_snapshot(github_id)   # {"easy","medium","hard","commits"} or None
    if current is None:
        return []                            # nothing connected → nothing to detect

    # Recent accepted problems, and how many of each difficulty were solved in the
    # last 24h (looked up per problem, since the submission list has no difficulty).
    user = get_user(github_id)
    recent = fetch_recent_ac(user.leetcode_username) if user and user.leetcode_username else []
    recent_slugs = {p["slug"] for p in recent}
    cutoff = time.time() - 86400
    solved_recently = {"easy": 0, "medium": 0, "hard": 0}
    for p in recent:
        if p["timestamp"] >= cutoff:
            prob = fetch_problem(p["slug"])
            if prob and prob["difficulty"] in solved_recently:
                solved_recently[prob["difficulty"]] += 1

    completed = []
    with Session(engine) as session:
        # Any auto-detectable task not done yet: a specific problem (slug), a
        # difficulty practice task (metric easy/medium/hard), or commits.
        tasks = session.exec(
            select(Task).where(
                Task.github_id == github_id,
                Task.completed == False,
            )
        ).all()
        for task in tasks:
            done = False

            # Specific problem → complete when it shows up in recent accepted solves.
            if task.leetcode_slug and task.leetcode_slug in recent_slugs:
                done = True
            elif task.metric in solved_recently:
                # Practice task → complete once enough of that difficulty were solved
                # in the last 24h (matches "solve N mediums today").
                if solved_recently[task.metric] >= (task.target or 1):
                    done = True
            elif task.metric == "commits":
                # Commits still use the baseline diff (no per-commit timestamp signal here).
                count = current["commits"]
                if task.baseline is None:
                    task.baseline = count        # first sighting → set the starting line
                    session.add(task)
                    continue
                if count - task.baseline >= (task.target or 1):
                    done = True

            if done:
                task.completed = True
                session.add(task)
                session.add(PointsLog(
                    github_id=github_id,
                    task_title=task.title,
                    points=task.points,
                    created_at=time.time(),
                ))
                completed.append(task.title)

        session.commit()
    return completed