import os
import time
from datetime import datetime, timezone, timedelta
from dotenv import load_dotenv
from sqlmodel import SQLModel, create_engine, Session, select
from models import User, Task, PointsLog, Snapshot
from crypto import encrypt_token
from leetcode import fetch_leetcode_stats
from planner import generate_roadmap

load_dotenv() 

DATABASE_URL = os.getenv('DATABASE_URL')

# Only build the engine if a URL is present, so importing this module doesn't
# crash when DATABASE_URL is missing (e.g. on Vercel, which isn't configured
# with it yet). Locally it comes from .env, so the engine works normally.
engine = create_engine(DATABASE_URL) if DATABASE_URL else None

def create_db_and_tables():
    SQLModel.metadata.create_all(engine)

def save_user(github_id, access_token):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user == None:
                user = User(github_id=github_id, github_token=encrypt_token(access_token))
        else:
                user.github_token = encrypt_token(access_token)
        session.add(user)
        session.commit()

def get_user(github_id):
    with Session(engine) as session:
        return session.exec(select(User).where(User.github_id == github_id)).first()

def set_leetcode_username(github_id, username):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user == None:
            return
        else:
            user.leetcode_username = username
        session.add(user)
        session.commit()

def save_leetcode_stats(github_id, easy, medium, hard):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is None:
            return
        user.leetcode_easy = easy
        user.leetcode_medium = medium
        user.leetcode_hard = hard
        user.leetcode_updated_at = time.time()   # record WHEN we cached it (Unix seconds)
        session.add(user)
        session.commit()


# A hardcoded starter roadmap. New users get seeded with these (Phase 3 template).
# (title, points, metric, target) — metric None = manual task (not auto-detected).
STARTER_TASKS = [
    ("Solve 5 easy LeetCode problems", 10, "easy", 5),
    ("Solve 3 medium LeetCode problems", 20, "medium", 3),
    ("Solve 1 hard LeetCode problem", 25, "hard", 1),
    ("Make 5 GitHub commits", 10, None, None),
    ("Merge 1 pull request", 15, None, None),
]

def get_tasks(github_id):
    # Just return stored tasks — they're generated by the AI planner when the
    # user sets a goal (never generated here, so page loads don't call Gemini).
    with Session(engine) as session:
        tasks = session.exec(select(Task).where(Task.github_id == github_id)).all()
        return [
            {"id": t.id, "title": t.title, "points": t.points, "completed": t.completed}
            for t in tasks
        ]


def replace_tasks(github_id, tasks):
    with Session(engine) as session:
        for old in session.exec(select(Task).where(Task.github_id == github_id)).all():
                session.delete(old)
        for t in tasks:
            session.add(Task(
                github_id=github_id,
                title=t["title"],
                points=t["points"],
                metric=t.get("metric"),
                target=t.get("target"),
            ))
        session.commit()


def set_goal_and_plan(github_id, goal):
    with Session(engine) as session:
        user = session.exec(select(User).where(User.github_id == github_id)).first()
        if user is None:
            return []
        user.big_goal = goal
        session.add(user)
        session.commit()
        tasks = generate_roadmap(goal) 
        replace_tasks(github_id, tasks)
        return get_tasks(github_id)

def complete_task(github_id, task_id):
    with Session(engine) as session:
        # Match BOTH id and github_id, so a user can only complete THEIR OWN task
        # (can't flip someone else's task by guessing an id).
        task = session.exec(
            select(Task).where(Task.id == task_id, Task.github_id == github_id)
        ).first()
        if task is None:
            return None
        if task.completed:
            return {"id": task.id, "points": 0}   # already done → don't double-award
        task.completed = True
        session.add(task)
        # Log the award (powers history + streak).
        session.add(PointsLog(
            github_id=github_id,
            task_title=task.title,
            points=task.points,
            created_at=time.time(),
        ))
        session.commit()
        return {"id": task.id, "points": task.points}


def get_points_log(github_id):
    with Session(engine) as session:
        logs = session.exec(
            select(PointsLog)
            .where(PointsLog.github_id == github_id)
            .order_by(PointsLog.created_at.desc())   # newest first
        ).all()
        return [
            {"task_title": l.task_title, "points": l.points, "created_at": l.created_at}
            for l in logs
        ]


def get_streak(github_id):
    # Consecutive days (UTC) on which the user earned points.
    with Session(engine) as session:
        logs = session.exec(select(PointsLog).where(PointsLog.github_id == github_id)).all()

    # Set of distinct dates the user was active.
    days = {datetime.fromtimestamp(l.created_at, tz=timezone.utc).date() for l in logs}
    if not days:
        return 0

    today = datetime.now(timezone.utc).date()
    # Anchor on today if active today, else yesterday (a streak isn't "broken"
    # until a whole day passes with no activity).
    if today in days:
        day = today
    elif (today - timedelta(days=1)) in days:
        day = today - timedelta(days=1)
    else:
        return 0

    # Walk backwards day by day while each day has activity.
    streak = 0
    while day in days:
        streak += 1
        day -= timedelta(days=1)
    return streak

def save_snapshot(github_id, easy, medium, hard, commit_count):
    with Session(engine) as session:
        snap = Snapshot(
            github_id=github_id,
            leetcode_easy=easy,
            leetcode_medium=medium,
            leetcode_hard=hard,
            commit_count=commit_count,
            created_at=time.time(),
        )
        session.add(snap)
        session.commit()

def get_last_snapshot(github_id):
    with Session(engine) as session:
        snap = session.exec(select(Snapshot).where(Snapshot.github_id == github_id).order_by(Snapshot.created_at.desc())).first()  
    if snap is None:
        return None
    return {
        "leetcode_easy": snap.leetcode_easy,
        "leetcode_medium": snap.leetcode_medium,
        "leetcode_hard": snap.leetcode_hard,
        "commit_count": snap.commit_count,
        "created_at": snap.created_at,
    }


def capture_snapshot(github_id):
    # Fetch the user's CURRENT LeetCode numbers and save them as a snapshot row.
    user = get_user(github_id)
    if user is None or user.leetcode_username is None:
        return None
    stats = fetch_leetcode_stats(user.leetcode_username)
    easy = stats.get("Easy", 0)
    medium = stats.get("Medium", 0)
    hard = stats.get("Hard", 0)
    # commit_count: GitHub commit detection is a later extension — LeetCode is the
    # clean auto-detect signal for now, so we store 0 for commits.
    save_snapshot(github_id, easy, medium, hard, 0)
    return {"easy": easy, "medium": medium, "hard": hard}


def get_all_user_ids():
    with Session(engine) as session:
        return [u.github_id for u in session.exec(select(User)).all()]


def run_detection(github_id):
    # 1. Capture a fresh snapshot; this also gives us the current counts.
    current = capture_snapshot(github_id)   # {"easy","medium","hard"} or None
    if current is None:
        return []                            # no LeetCode username → nothing to detect

    completed = []
    with Session(engine) as session:
        # Only auto-detectable (metric set) tasks that aren't done yet.
        tasks = session.exec(
            select(Task).where(
                Task.github_id == github_id,
                Task.completed == False,
                Task.metric != None,
            )
        ).all()
        for task in tasks:
            count = current[task.metric]     # current count for this task's metric

            if task.baseline is None:
                # First time we've seen this task → record the starting line.
                task.baseline = count
                session.add(task)
            elif count - task.baseline >= task.target:
                # Gained enough since the baseline → auto-complete + log the points.
                task.completed = True
                session.add(task)
                session.add(PointsLog(
                    github_id=github_id,
                    task_title=task.title,
                    points=task.points,
                    created_at=time.time(),
                ))
                completed.append(task.title)

        session.commit()
    return completed